### ISSUE TITLE
Is there way to host keys on my own

### ISSUE THREAD

**Issue by iamatulsingh** [libin9iOak/ja-netfilter-all#19]
I just wanted to know how those code in the https://3.jetbra.in are generated. How can I host my own service to those servers listed in it?

**Comment by libin9iOak** [comment]
no，you can't .



| |
libin9ioak
|
|
***@***.***
|




---- Replied Message ----
| From | Atul ***@***.***> |
| Date | 05/20/2023 03:38 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [libin9iOak/ja-netfilter-all] Is there way to host keys on my own (Issue #19) |

I just wanted to know how those code in the https://3.jetbra.in are generated. How can I host my own service to those servers listed in it?
