### ISSUE TITLE
Start failed (2022.2.1)

### ISSUE THREAD

**Issue by wiknew1** [libin9iOak/ja-netfilter-all#2]
Products - WebStorm, CLion
Version - 2022.2.1
OS - Windows 11
ja-netfilter-all version - Latest source

![image](https://user-images.githubusercontent.com/60450988/187354516-316dbb73-c107-4dfe-9b91-5e8bb2ed3ad9.png)

**Comment by libin9iOak** [comment]
路径



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/30/2022 13:13 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [libin9iOak/ja-netfilter-all] Start failed (2022.2.1) (Issue #2) |

Products - WebStorm, CLion
Version - 2022.2.1
OS - Windows 11
ja-netfilter-all version - Latest source

**Comment by wiknew1** [comment]
@libin9iOak thank you for the response.

Path? I'm sorry I didn't understand that. 🤔

**Comment by libin9iOak** [comment]
检查一下路径配置争取了吗



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/31/2022 10:41 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [libin9iOak/ja-netfilter-all] Start failed (2022.2.1) (Issue #2) |

@libin9iOak thank you for the response.

Path? I'm sorry I didn't understand that. 🤔

**Comment by wiknew1** [comment]
So apparently my NAT driver service wasn't running and all I had to do was `net start winnat`. All good now. 😊
