### ISSUE TITLE
大神，2022-2-1目前支持吗？

### ISSUE THREAD

**Issue by ruinmi** [libin9iOak/ja-netfilter-all#5]

**Comment by libin9iOak** [comment]
支持最新版



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月07日 21:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [libin9iOak/ja-netfilter-all] 大神，2022-2-1目前支持吗？ (Issue #5) |

**Comment by ruinmi** [comment]
> 支持最新版
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年09月07日 21:29 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [libin9iOak/ja-netfilter-all] 大神，2022-2-1目前支持吗？ (Issue #5) | — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

忘了加那两行，谢谢了
